# Generated by Django 5.2.14 on 2026-05-06 00:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('DOB', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'USER',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'BOOKING',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category_name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'CATEGORY',
            },
        ),
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('provider', models.OneToOneField(db_column='provider_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='service_provider', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('average_rating', models.FloatField(blank=True, null=True)),
                ('service_area', models.TextField()),
                ('service_distance', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'SERVICE_PROVIDER',
            },
        ),
        migrations.CreateModel(
            name='BackgroundCheck',
            fields=[
                ('check_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('report', models.TextField()),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'BACKGROUND_CHECK',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('booking', models.OneToOneField(db_column='booking_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.booking')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField()),
                ('payment_method', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'PAYMENT',
            },
        ),
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('dispute_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('reason', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('booking', models.ForeignKey(db_column='booking_id', on_delete=django.db.models.deletion.CASCADE, to='core.booking')),
                ('claimant', models.ForeignKey(db_column='claimant_id', on_delete=django.db.models.deletion.CASCADE, related_name='disputes_as_claimant', to=settings.AUTH_USER_MODEL)),
                ('defendant', models.ForeignKey(db_column='defendant_id', on_delete=django.db.models.deletion.CASCADE, related_name='disputes_as_defendant', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'DISPUTE',
            },
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('job_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('service_area', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.CASCADE, to='core.category')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'JOB_POSTING',
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='job',
            field=models.ForeignKey(db_column='job_id', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='core.jobposting'),
        ),
        migrations.AddField(
            model_name='booking',
            name='provider',
            field=models.ForeignKey(db_column='provider_id', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='core.serviceprovider'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('booking', models.OneToOneField(db_column='booking_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.booking')),
                ('rating', models.IntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('review_date', models.DateField()),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'REVIEW',
            },
        ),
        migrations.CreateModel(
            name='Provides',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.CASCADE, to='core.category')),
                ('provider', models.ForeignKey(db_column='provider_id', on_delete=django.db.models.deletion.CASCADE, related_name='provides', to='core.serviceprovider')),
            ],
            options={
                'db_table': 'PROVIDES',
                'constraints': [models.UniqueConstraint(fields=('provider', 'category'), name='uniq_provider_category')],
            },
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(fields=('job', 'provider'), name='uniq_booking_job_provider'),
        ),
    ]
